# -*- coding: utf-8 -*-
"""Minh_Thai_grade_the_exams.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11_0tABq8jKTTGE3rA9vTN4csHK9XqIrm
"""

# from google.colab import drive
# drive.mount('/content/drive')

import pandas as pd
import numpy as np

def task_1():
    while True:
        # Bước 1: Cho phép người dùng nhập tên tệp
        filename = input("Enter a class file to grade (i.e. class1 for class1.txt): ").strip()

        # Tự động thêm đuôi .txt nếu người dùng quên nhập
        if not filename.endswith('.txt'):
            full_filename = filename + ".txt"
        else:
            full_filename = filename

        # Bước 2: Sử dụng try/except để mở tệp
        try:
            # Thử đọc 0 dòng dữ liệu để xác nhận file tồn tại và có thể truy cập
            pd.read_csv(full_filename, nrows=0)

            # Nếu thành công, in thông báo xác nhận
            print(f"Successfully opened {full_filename}")
            return full_filename # Trả về tên file để dùng cho Task 2
            break

        except FileNotFoundError:
            # Nếu không tìm thấy tệp, thông báo và nhắc lại người dùng
            print("File cannot be found.")
        except Exception as e:
            # Xử lý các lỗi phát sinh khác (nếu có) một cách chung chung
            print(f"An error occurred: {e}")

if __name__ == "__main__":
    current_file = task_1()

def task_2(full_filename):
    print("\n**** ANALYZING ****")

    try:
        # Đọc toàn bộ file, coi mỗi dòng là một chuỗi văn bản duy nhất
        # header=None vì file không có dòng tiêu đề
        df = pd.read_csv(full_filename, header=None, sep="\t", names=["raw_line"], engine='python')

        # 1. Tách chuỗi theo dấu phẩy (tương đương phương pháp split)
        # split_series sẽ là một Series chứa các list
        split_series = df["raw_line"].str.split(',')

        # 2. Kiểm tra điều kiện 1: Phải chứa đúng 26 giá trị
        is_correct_length = split_series.apply(len) == 26

        # 3. Kiểm tra điều kiện 2: Định dạng ID (N + 8 chữ số)
        student_ids = split_series.str[0] # Lấy phần tử đầu tiên của mỗi list
        is_valid_id = (student_ids.str.len() == 9) & \
                      (student_ids.str.startswith('N')) & \
                      (student_ids.str.slice(1).str.isdigit())

        # Tạo mask cho các dòng hợp lệ (thỏa cả 2 điều kiện)
        valid_mask = is_correct_length & is_valid_id

        # 4. Báo cáo các dòng lỗi
        # Sử dụng NumPy để tìm chỉ số (index) của các dòng không hợp lệ
        invalid_indices = np.where(~valid_mask)[0]

        for idx in invalid_indices:
            line_content = df.iloc[idx]["raw_line"]
            # Phân loại lỗi để in thông báo tương ứng
            if not is_correct_length.iloc[idx]:
                print(f"Invalid line of data: does not contain exactly 26 values:")
            else:
                print(f"Invalid line of data: N# is invalid")
            print(line_content)

        if len(invalid_indices) == 0:
            print("No errors found!")

        # 5. Báo cáo tổng kết (REPORT)
        total_valid = np.sum(valid_mask)
        total_invalid = len(df) - total_valid

        print("\n**** REPORT ****")
        print(f"Total valid lines of data: {total_valid}")
        print(f"Total invalid lines of data: {total_invalid}")

        # Trả về DataFrame chỉ chứa các dòng hợp lệ để dùng cho Task 3 (chấm điểm)
        return split_series[valid_mask]

    except Exception as e:
        print(f"Error during analysis: {e}")
        return None

# Cách gọi trong khối main
if __name__ == "__main__":
    # Giả sử current_file lấy từ Task 1
    current_file = task_1()
    valid_data = task_2(current_file)

valid_data_series = task_2(current_file)
def task_3(valid_data_series):
    """
    valid_data_series: Một Series chứa các list (mỗi list 26 phần tử) từ Task 2.
    """
    if valid_data_series is None or valid_data_series.empty:
        print("No valid data to grade.")
        return

    # 1. Khai báo đáp án (Rubric)
    answer_key = "B,A,D,D,C,B,D,A,C,C,D,B,A,B,A,C,B,D,A,C,A,A,B,D,D"
    key_np = np.array(answer_key.split(","))

    # 2. Chuyển đổi dữ liệu học sinh thành mảng NumPy 2D
    # Chỉ lấy từ cột index 1 đến 25 (bỏ qua cột ID ở index 0)
    data_matrix = np.array(valid_data_series.tolist())
    student_answers = data_matrix[:, 1:]

    # 3. Tính toán điểm số bằng Vectorization của NumPy
    # Kiểm tra các điều kiện trên toàn bộ mảng
    is_correct = (student_answers == key_np)
    is_skipped = (student_answers == "")
    is_incorrect = ~(is_correct | is_skipped)

    # Tính tổng điểm cho từng học sinh: Đúng (+4), Trống (0), Sai (-1)
    # axis=1 giúp tính tổng theo hàng (từng học sinh)
    scores = (np.sum(is_correct, axis=1) * 4) + (np.sum(is_incorrect, axis=1) * -1)

    # 4. Tính toán các thông số thống kê
    mean_score = np.mean(scores)
    highest_score = np.max(scores)
    lowest_score = np.min(scores)
    range_of_scores = highest_score - lowest_score
    median_score = np.median(scores)

    # 5. In báo cáo thống kê (Format theo yêu cầu đề bài)
    #
    print(f"Mean (average) score: {mean_score:.2f}")
    print(f"Highest score: {highest_score}")
    print(f"Lowest score: {lowest_score}")
    print(f"Range of scores: {range_of_scores}")
    # Chuyển về số nguyên nếu median là số nguyên để khớp mẫu đầu ra
    print(f"Median score: {int(median_score) if median_score % 1 == 0 else median_score}")

    return scores, data_matrix[:, 0] # Trả về điểm và ID để dùng cho Task 4

if __name__ == "__main__":
    scores, student_ids = task_3(valid_data_series)

# 1. Chuẩn bị dữ liệu từ các Task trước
original_filename = current_file
scores, student_ids = task_3(valid_data_series)

# 2. Định nghĩa "cách làm" Task 4 (giữ nguyên code của bạn)
def task_4(original_filename, student_ids, scores):
    # Tạo tên file: class1.txt -> class1_grades.txt
    output_filename = original_filename.replace(".txt", "") + "_grades.txt"

    # Tạo DataFrame để quản lý dữ liệu
    results_df = pd.DataFrame({
        'id': student_ids,
        'score': scores
    })

    # Xuất ra file .txt theo đúng định dạng: ID, điểm
    results_df.to_csv(output_filename, header=None, index=False, sep=',')
    print(f"Results saved to {output_filename}")

# 3. QUAN TRỌNG NHẤT: Đây là lệnh để Python THỰC HIỆN việc tạo file
task_4(original_filename, student_ids, scores)